#!/bin/bash
mkdir /var/log/userwgcheck
checkpath="/var/log/userwgcheck"
declare -A clients_key
read $(wg show all dump | awk '$6 == 0 {print $2}')

day=$(date +%a)
queue=/opt/wireguard_server/usercheck.txt
if [[ ! -f "${queue}" ]]; then
  touch /opt/wireguard_server/usercheck.txt
fi

case $day in
Mon)
  filename="$checkpath/mon.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/mon.txt") <(sort "$checkpath/sun.txt") >"$queue"
  ;;
Tue)
  filename="$checkpath/tue.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/tue.txt") <(sort "$checkpath/mon.txt") >"$queue"
  ;;
Wed)
  filename="$checkpath/wed.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/wed.txt") <(sort "$checkpath/tue.txt") >"$queue"
  ;;
Thu)
  filename="$checkpath/thu.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/thu.txt") <(sort "$checkpath/wed.txt") >"$queue"
  ;;
Fri)
  filename="$checkpath/fri.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/fri.txt") <(sort "$checkpath/thu.txt") >"$queue"
  ;;
Sat)
  filename="$checkpath/sat.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/sat.txt") <(sort "$checkpath/fri.txt") >"$queue"
  ;;
Sun)
  filename="$checkpath/sun.txt"
  echo $clients_key >$filename
  comm -12 <(sort "$checkpath/sun.txt") <(sort "$checkpath/sat.txt") >"$queue"
  ;;
esac
